name = "comics-ts"
workers_dev = true
routes = ['comics.wangpedersen.com/*']
main = "dist/worker.js"
compatibility_date = "2023-02-08"

[site]
bucket = "./dist/public"

[build]
command = "npm install && npm run build"

[[kv_namespaces]]
binding = "comicsKv"
id = "f2794c1d4ee244a0aab2bd9fcbf46efe"

[triggers]
crons = ["0 */1 * * *"]
