name = "comics-ts"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
routes = ['comics2.wangpedersen.com/*']

[site]
bucket = "./dist/public"
entry-point = "."

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
